### ISSUE TITLE
Channel LUA error

### ISSUE THREAD

**Issue by lightbored** [TimothyLuke/GCDReborn#4]
Would get a LUA error in Cast.lua on line 356 because of trying to do a mathematical operation on a Boolean value.   UnitChannelInfo changed for patch 8.0.1 to fewer parameters, so updating line 355 from:
_, _, _, _, castStartTime, castEndTime = UnitChannelInfo(unit)
to:
_, _, _, castStartTime, castEndTime = UnitChannelInfo(unit)
corrected the issue for me.
Updated based on API info from https://wow.gamepedia.com/API_UnitChannelInfo
![Screenshot](https://user-images.githubusercontent.com/10554615/60012950-3bb5e200-964b-11e9-82bb-a0182b19144a.png)

**Comment by TimothyLuke** [comment]
Fixed in next release
